// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: skillforge.proto

package skillforge

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TalosAgent_Query_FullMethodName = "/skillforge.TalosAgent/Query"
)

// TalosAgentClient is the client API for TalosAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TalosAgentClient interface {
	// Receives a user query and returns a response.
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type talosAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewTalosAgentClient(cc grpc.ClientConnInterface) TalosAgentClient {
	return &talosAgentClient{cc}
}

func (c *talosAgentClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, TalosAgent_Query_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TalosAgentServer is the server API for TalosAgent service.
// All implementations must embed UnimplementedTalosAgentServer
// for forward compatibility
type TalosAgentServer interface {
	// Receives a user query and returns a response.
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	mustEmbedUnimplementedTalosAgentServer()
}

// UnimplementedTalosAgentServer must be embedded to have forward compatible implementations.
type UnimplementedTalosAgentServer struct {
}

func (UnimplementedTalosAgentServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedTalosAgentServer) mustEmbedUnimplementedTalosAgentServer() {}

// UnsafeTalosAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TalosAgentServer will
// result in compilation errors.
type UnsafeTalosAgentServer interface {
	mustEmbedUnimplementedTalosAgentServer()
}

func RegisterTalosAgentServer(s grpc.ServiceRegistrar, srv TalosAgentServer) {
	s.RegisterService(&TalosAgent_ServiceDesc, srv)
}

func _TalosAgent_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalosAgentServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalosAgent_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalosAgentServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TalosAgent_ServiceDesc is the grpc.ServiceDesc for TalosAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TalosAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "skillforge.TalosAgent",
	HandlerType: (*TalosAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _TalosAgent_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "skillforge.proto",
}

const (
	SkillforgeEngine_GetCbe_FullMethodName = "/skillforge.SkillforgeEngine/GetCbe"
)

// SkillforgeEngineClient is the client API for SkillforgeEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SkillforgeEngineClient interface {
	// Requests a CBE based on user data.
	GetCbe(ctx context.Context, in *CbeRequest, opts ...grpc.CallOption) (*CbeResponse, error)
}

type skillforgeEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewSkillforgeEngineClient(cc grpc.ClientConnInterface) SkillforgeEngineClient {
	return &skillforgeEngineClient{cc}
}

func (c *skillforgeEngineClient) GetCbe(ctx context.Context, in *CbeRequest, opts ...grpc.CallOption) (*CbeResponse, error) {
	out := new(CbeResponse)
	err := c.cc.Invoke(ctx, SkillforgeEngine_GetCbe_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkillforgeEngineServer is the server API for SkillforgeEngine service.
// All implementations must embed UnimplementedSkillforgeEngineServer
// for forward compatibility
type SkillforgeEngineServer interface {
	// Requests a CBE based on user data.
	GetCbe(context.Context, *CbeRequest) (*CbeResponse, error)
	mustEmbedUnimplementedSkillforgeEngineServer()
}

// UnimplementedSkillforgeEngineServer must be embedded to have forward compatible implementations.
type UnimplementedSkillforgeEngineServer struct {
}

func (UnimplementedSkillforgeEngineServer) GetCbe(context.Context, *CbeRequest) (*CbeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCbe not implemented")
}
func (UnimplementedSkillforgeEngineServer) mustEmbedUnimplementedSkillforgeEngineServer() {}

// UnsafeSkillforgeEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkillforgeEngineServer will
// result in compilation errors.
type UnsafeSkillforgeEngineServer interface {
	mustEmbedUnimplementedSkillforgeEngineServer()
}

func RegisterSkillforgeEngineServer(s grpc.ServiceRegistrar, srv SkillforgeEngineServer) {
	s.RegisterService(&SkillforgeEngine_ServiceDesc, srv)
}

func _SkillforgeEngine_GetCbe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CbeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillforgeEngineServer).GetCbe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillforgeEngine_GetCbe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillforgeEngineServer).GetCbe(ctx, req.(*CbeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SkillforgeEngine_ServiceDesc is the grpc.ServiceDesc for SkillforgeEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkillforgeEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "skillforge.SkillforgeEngine",
	HandlerType: (*SkillforgeEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCbe",
			Handler:    _SkillforgeEngine_GetCbe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "skillforge.proto",
}
